pipeline_tiktok_ads:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: data-ads-external-report-prod
      dataset: "{{ env_var('COMPANY') }}_dataset_tiktok_api_mart"
      location: asia-southeast1
      threads: 2